apiVersion: v1
kind: Service
metadata:
    name: "aksworkshop14905-6870"
    labels:
        app: "aksworkshop14905-6870"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksworkshop14905-6870"