on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acr32057.azurecr.io
        username: ${{ secrets.acr_acr32057_username }}
        password: ${{ secrets.acr_acr32057_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acr32057.azurecr.io/aksworkshop14905:${{ github.sha }}
        docker push acr32057.azurecr.io/aksworkshop14905:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksworkshop14905_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksworkshop149058fe0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksworkshop149058fe0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksworkshop149058fe0
        container-registry-url: acr32057.azurecr.io
        container-registry-username: ${{ secrets.acr_acr32057_username }}
        container-registry-password: ${{ secrets.acr_acr32057_password }}
        secret-name: aksworkshop1dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aksworkshop149058fe0
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acr32057.azurecr.io/aksworkshop14905:${{ github.sha }}
        imagepullsecrets: |
          aksworkshop1dockerauth